In [ ]:
!pip install -U spacy

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.7)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.17.4)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.11.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.12/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.8.3)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.22.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

In [ ]:
import spacy
from spacy import displacy
from collections import Counter
import pandas as pd
pd.options.display.max_rows = 600
pd.options.display.max_colwidth = 400

In [ ]:
!python -m spacy download ru_core_news_md

Collecting ru-core-news-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/ru_core_news_md-3.8.0/ru_core_news_md-3.8.0-py3-none-any.whl (41.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.9/41.9 MB 19.4 MB/s eta 0:00:00
Collecting pymorphy3>=1.0.0 (from ru-core-news-md==3.8.0)
  Downloading pymorphy3-2.0.4-py3-none-any.whl.metadata (2.4 kB)
Collecting dawg2-python>=0.8.0 (from pymorphy3>=1.0.0->ru-core-news-md==3.8.0)
  Downloading dawg2_python-0.9.0-py3-none-any.whl.metadata (7.5 kB)
Collecting pymorphy3-dicts-ru (from pymorphy3>=1.0.0->ru-core-news-md==3.8.0)
  Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: setuptools>=68.2.2 in /usr/local/lib/python3.12/dist-packages (from pymorphy3>=1.0.0->ru-core-news-md==3.8.0) (75.2.0)
Downloading pymorphy3-2.0.4-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.1/54.1 kB 3.1 MB/s eta 0:00:00
Downloading dawg2_python-0.9.0-py3-none-any.whl (9.3 kB)
Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 87.4 MB/s eta 0:00:00
Installing collected packages: pymorphy3-dicts-ru, dawg2-python, pymorphy3, ru-core-news-md
Successfully installed dawg2-python-0.9.0 pymorphy3-2.0.4 pymorphy3-dicts-ru-2.4.417150.4580142 ru-core-news-md-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('ru_core_news_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import ru_core_news_md
nlp = ru_core_news_md.load()

In [ ]:
filepath = 'text.txt'
text = open(filepath, encoding='utf-8').read()
document = nlp(text)

In [ ]:
document.ents

(Володя,
 Петербурге,
 Москву,
 Москву,
 Малой Никитской,
 Сыромятниковым,
 Москвы,
 Володя,
 Марфа Коренева,
 Марта,
 Кореневой,
 Москвы,
 Марта,
 Володи Марта,
 Мартой,
 Марте,
 Кореневой,
 Володя,
 Петербурге,
 Москву,
 Листьеву,
 Марту,
 Кореневу,
 Марты,
 Марты,
 Володя,
 Малой Никитской,
 Марте,
 Марфа Коренева,
 Володя,
 Марте,
 Маремьянова,
 Марфу,
 Володя,
 Марту,
 Метербурге,
 Москву,
 Марту,
 Марта,
 Володю)

In [ ]:
for named_entity in document.ents:
    print(named_entity, named_entity.label_)

Володя PER
Петербурге LOC
Москву LOC
Москву LOC
Малой Никитской LOC
Сыромятниковым PER
Москвы LOC
Володя PER
Марфа Коренева PER
Марта PER
Кореневой PER
Москвы LOC
Марта PER
Володи Марта PER
Мартой PER
Марте PER
Кореневой PER
Володя PER
Петербурге LOC
Москву LOC
Листьеву PER
Марту PER
Кореневу PER
Марты PER
Марты PER
Володя PER
Малой Никитской LOC
Марте PER
Марфа Коренева PER
Володя PER
Марте PER
Маремьянова PER
Марфу PER
Володя PER
Марту PER
Метербурге LOC
Москву LOC
Марту LOC
Марта PER
Володю PER

In [ ]:
for named_entity in document.ents:
    if named_entity.label_ == "PER":
        print(named_entity)

Володя
Сыромятниковым
Володя
Марфа Коренева
Марта
Кореневой
Марта
Володи Марта
Мартой
Марте
Кореневой
Володя
Листьеву
Марту
Кореневу
Марты
Марты
Володя
Марте
Марфа Коренева
Володя
Марте
Маремьянова
Марфу
Володя
Марту
Марта
Володю

In [ ]:
for named_entity in document.ents:
    if named_entity.label_ == "LOC":
        print(named_entity)

Петербурге
Москву
Москву
Малой Никитской
Москвы
Москвы
Петербурге
Москву
Малой Никитской
Метербурге
Москву
Марту

In [ ]:
import math
number_of_chunks = 80

chunk_size = math.ceil(len(text) / number_of_chunks)

text_chunks = []

for number in range(0, len(text), chunk_size):
    text_chunk = text[number:number+chunk_size]
    text_chunks.append(text_chunk)

In [ ]:
chunked_documents = list(nlp.pipe(text_chunks))

In [ ]:
people = []

for document in chunked_documents:
    for named_entity in document.ents:
        if named_entity.label_ == "PER":
            people.append(named_entity.text)

people_tally = Counter(people)

df = pd.DataFrame(people_tally.most_common(), columns=['character', 'count'])
df

        character  count
0          Володя      5
1           Марта      2
2           Марте      2
3            Март      2
4              Ма      1
5   лой Никитской      1
6           осквы      1
7    Марфа Корене      1
8            Коре      1
9            Воло      1
10       ди Марта      1
11         Мартой      1
12      Кореневой      1
13          олодя      1
14       Листьеву      1
15          Марту      1
16          Марты      1
17  Марфа Коренев      1
18          специ      1
19    Маремьянова      1
20          Марфу      1

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1DDJZWt18rMZXLd9rF_btb-0XBUYMzzEGfZt45lsv6hY/edit#gid=0

In [ ]:
places = []
for document in chunked_documents:
    for named_entity in document.ents:
        if named_entity.label_ == "LOC":
            places.append(named_entity.text)

places_tally = Counter(places)

df = pd.DataFrame(places_tally.most_common(), columns=['place', 'count'])
df

             place  count
0           Москву      4
1          Петербу      2
2            Марту      2
3                М      1
4            Марта      1
5           Москвы      1
6         Кореневу      1
7  Малой Никитской      1
8       Метербурге      1
9           Володю      1

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/13-SZYqxk15XdwmwEogIPZBNT1jshbmYrI4Nm-Z-F4K0/edit#gid=0

In [ ]:
from IPython.display import Markdown, display
import re

def get_ner_in_context(keyword, document, desired_ner_labels= False):

    if desired_ner_labels != False:
        desired_ner_labels = desired_ner_labels
    else:
        # all possible labels
        desired_ner_labels = list(nlp.get_pipe('ner').labels)

    #Iterate through all the sentences in the document and pull out the text of each sentence
    for sentence in document.sents:
        #process each sentence
        sentence_doc = nlp(sentence.text)
        for named_entity in sentence_doc.ents:
            #Check to see if the keyword is in the sentence (and ignore capitalization by making both lowercase)
            if keyword.lower() in named_entity.text.lower()  and named_entity.label_ in desired_ner_labels:
                #Use the regex library to replace linebreaks and to make the keyword bolded, again ignoring capitalization
                #sentence_text = sentence.text

                sentence_text = re.sub('\n', ' ', sentence.text)
                sentence_text = re.sub(f"{named_entity.text}", f"**{named_entity.text}**", sentence_text, flags=re.IGNORECASE)

                print('---')
                display(Markdown(f"**{named_entity.label_}**"))
                display(Markdown(sentence_text))

In [ ]:
for document in chunked_documents:
    get_ner_in_context('Марта', document)

---

**LOC**

сто **Марта** – вернулас

---

**PER**

о **Марта** покорила все

---

**PER**

**ди Марта** всегда была

In [ ]:
filepath = 'text1.txt'
text = open(filepath, encoding='utf-8').read()
document = nlp(text)

In [ ]:
for token in document:
    print(token.lemma_, token.pos_, token.dep_)

осенний ADJ amod
визит NOUN nsubj
на ADP case
никитский ADJ nmod

 SPACE dep
быть VERB nmod
холодный ADJ amod
, PUNCT punct
двадцатиградусный ADJ conj
ноябрьский ADJ amod
день NOUN ROOT
. PUNCT punct
сам ADJ amod
александр PROPN nsubj
чувствовать VERB ROOT
себя PRON obj
виноватый ADJ xcomp
и CCONJ cc
странный ADJ conj
, PUNCT punct
стоить VERB advcl
неодетый VERB obj
у ADP case
окно NOUN obl
свой DET det
старый ADJ amod
квартира NOUN nmod
на ADP case
никитский ADJ nmod
. PUNCT punct
за ADP case
окно NOUN obl
кружиться VERB ROOT
лёгкий ADJ amod
первый ADJ amod
снег NOUN nsubj
, PUNCT punct
делать VERB advcl
большой ADJ amod
город NOUN obj
тёмный ADJ xcomp
и CCONJ cc
чужой ADJ conj
. PUNCT punct


 SPACE dep
этот DET det
последний ADJ amod
визит NOUN nsubj
к ADP case
пожилой ADJ amod
экономка NOUN nmod
марфа PROPN appos
быть AUX cop
важный ADJ ROOT
и CCONJ cc
трудный ADJ conj
. PUNCT punct
он PRON nsubj
вспомнить VERB ROOT
её DET det
письмо NOUN obj
— PUNCT punct
нежный ADJ amod
, PUNCT punct
трусливый ADJ amod
почерк NOUN parataxis
на ADP case
жёлтый ADJ amod
лист NOUN nmod
. PUNCT punct
в ADP case
нём NOUN obl
она PRON nsubj
упоминать VERB ROOT
какой DET det
- DET det
то DET det
знаменитый ADJ amod
талантливый ADJ amod
молодой ADJ amod
человек NOUN obj
, PUNCT punct
похожий ADJ amod
на ADP case
него PRON obl
самого ADJ amod
, PUNCT punct
но CCONJ cc
это PRON nsubj
быть AUX cop
совсем ADV advmod
другой ADJ amod
человек NOUN conj
, PUNCT punct
с ADP case
другими ADJ amod
цель NOUN conj
. PUNCT punct


 SPACE dep
он DET det
мысль NOUN nsubj
прервать VERB ROOT
громкий ADJ amod
звенящий ADJ amod
звонок NOUN obj
. PUNCT punct
на ADP case
порог NOUN obl
стоять VERB ROOT
она PRON nsubj
— PUNCT punct
не PART advmod
марфа PROPN parataxis
, PUNCT punct
а CCONJ cc
молоденький ADJ amod
хорошенький ADJ amod
девушка NOUN conj
с ADP case
больший ADJ amod
сиять VERB amod
глаз NOUN nmod
. PUNCT punct
это PRON nsubj
быть AUX cop
анна PROPN ROOT
, PUNCT punct
её PRON nmod
внучка NOUN conj
. PUNCT punct
в ADP case
её DET det
взгляд NOUN obl
было AUX cop
что PRON nsubj
- PRON nsubj
то PRON nsubj
необычный ADJ amod
, PUNCT punct
радостный ADJ conj
и CCONJ cc
беспокойный ADJ conj
одновременно ADV ROOT
. PUNCT punct


 SPACE dep
— PUNCT punct
бабушка NOUN nsubj
ждёт ADJ ROOT
вас PRON obj
, PUNCT punct
— PUNCT punct
сказать VERB parataxis
она PRON nsubj
тихим ADJ amod
, PUNCT punct
нежный ADJ amod
голос NOUN iobj
. PUNCT punct


 SPACE dep
комната NOUN nsubj
марфы PROPN appos
быть AUX cop
маленький ADJ ROOT
, PUNCT punct
простой ADJ conj
, PUNCT punct
пропахнуть VERB conj
тёплый ADJ amod
хлеб NOUN iobj
и CCONJ cc
что PRON conj
- PRON conj
то PRON conj
душистый ADJ amod
, PUNCT punct
розовый ADJ conj
. PUNCT punct
сама ADJ amod
она PRON nsubj
, PUNCT punct
равнодушный ADJ amod
и CCONJ cc
спокойный ADJ conj
, PUNCT punct
сидеть VERB ROOT
в ADP case
кресло NOUN obl
. PUNCT punct
её DET det
рука NOUN nsubj
, PUNCT punct
тонкий ADJ amod
и CCONJ cc
прозрачный ADJ conj
, PUNCT punct
лежать VERB ROOT
на ADP case
колено NOUN obl
. PUNCT punct
Рядом ADV advmod
на ADP case
старенький ADJ amod
столик NOUN obl
стоять VERB ROOT
крошечный ADJ amod
зелёный ADJ amod
кактус NOUN nsubj
в ADP case
голубой ADJ amod
горшок NOUN nmod
— PUNCT punct
милый ADJ case
, PUNCT punct
невольный ADJ amod
подарок NOUN parataxis
от ADP case
кто PRON nmod
- PRON nmod
то PRON nmod
чужой ADJ amod
. PUNCT punct


 SPACE dep
разговор NOUN nsubj
быть AUX cop
тяжёлый ADJ ROOT
, PUNCT punct
однообразный ADJ conj
. PUNCT punct
александр PROPN nsubj
чувствовать VERB ROOT
себя PRON obj
неловко ADV advmod
, PUNCT punct
он DET det
слово NOUN nsubj
казаться VERB conj
неестественный ADJ xcomp
, PUNCT punct
пошлый ADJ conj
. PUNCT punct
он PRON nsubj
говорить VERB ROOT
о ADP case
порядочный ADJ amod
человек NOUN obl
, PUNCT punct
о ADP case
должный ADJ amod
поведение NOUN conj
, PUNCT punct
но CCONJ cc
звучать VERB conj
это PRON nsubj
фальшивый ADJ advmod
. PUNCT punct
весь DET det
это PRON nsubj
было AUX cop
неправда NOUN ROOT
, PUNCT punct
бесполезный ADJ conj
и CCONJ cc
нужный ADJ conj
только PART advmod
ему PRON iobj
самому ADJ conj
. PUNCT punct


 SPACE dep
вдруг ADV advmod
он DET det
взгляд NOUN nsubj
упасть VERB ROOT
на ADP case
старый ADJ amod
фотография NOUN obl
. PUNCT punct
на ADP case
ней PRON ROOT
быть AUX cop
красивый ADJ amod
молодой ADJ amod
человек NOUN nsubj
с ADP case
умный ADJ amod
глаз NOUN nmod
, PUNCT punct
похожий ADJ amod
на ADP case
него PRON obl
как SCONJ case
два NUM nummod:gov
капля NOUN obl
вода NOUN nmod
. PUNCT punct
это PRON nsubj
быть AUX cop
его PRON nmod
родной ADJ amod
дед NOUN ROOT
, PUNCT punct
о ADP case
котором PRON obl
он PRON nsubj
почти ADV advmod
ничто PRON obj
не PART advmod
знать VERB acl:relcl
. PUNCT punct
и CCONJ cc
тут ADV advmod
он PRON nsubj
всё PRON obj
понять VERB ROOT
. PUNCT punct
этот DET det
визит NOUN nsubj
быть AUX cop
не PART advmod
случайный ADJ ROOT
. PUNCT punct
это PRON nsubj
быть AUX cop
необходимый ADJ amod
, PUNCT punct
главный ADJ amod
встреча NOUN ROOT
он DET det
жизнь NOUN nmod
. PUNCT punct


 SPACE dep
он PRON nsubj
взглянуть VERB ROOT
на ADP case
анна PROPN obl
. PUNCT punct
она PRON nsubj
смотреть VERB ROOT
на ADP case
него PRON obl
не PART advmod
равнодушный ADJ acl
, PUNCT punct
а CCONJ cc
живой ADJ amod
глаз NOUN conj
, PUNCT punct
полными VERB acl
тайный ADJ amod
ожидание NOUN obj
. PUNCT punct
и CCONJ cc
в ADP case
этот DET det
мгновенный ADJ amod
, PUNCT punct
счастливый ADJ conj
миг NOUN obl
он PRON nsubj
почувствовать VERB ROOT
не PART advmod
холодный ADJ amod
ужас NOUN obj
одиночество NOUN nmod
, PUNCT punct
а CCONJ cc
тёплый ADJ amod
радостный ADJ amod
чувство NOUN conj
связь NOUN nmod
. PUNCT punct
связь NOUN ROOT
с ADP case
этот DET det
маленький ADJ amod
мир NOUN nmod
, PUNCT punct
с ADP case
этот DET det
милый ADJ amod
девушка NOUN conj
, PUNCT punct
с ADP case
этот DET det
старый ADJ amod
женщина NOUN conj
, PUNCT punct
хранить VERB acl
память NOUN obj
о ADP case
он DET det
кровь NOUN nmod
. PUNCT punct


 SPACE dep
он PRON nsubj
уйти VERB ROOT
от ADP case
них PRON obl
не PART advmod
с ADP case
тяжёлый ADJ amod
сердце NOUN obl
, PUNCT punct
а CCONJ cc
с ADP case
лёгкий ADJ conj
. PUNCT punct
на ADP case
улица NOUN obl
было AUX cop
ещё ADV advmod
холодный ADJ ROOT
, PUNCT punct
тёмно ADJ conj
и CCONJ cc
сырой ADJ conj
, PUNCT punct
но CCONJ cc
в ADP case
душа NOUN obl
у ADP case
него PRON obl
петь VERB conj
весенний ADJ amod
птица NOUN nsubj
. PUNCT punct
он PRON nsubj
нашёл ADJ advmod
нечто PRON ROOT
больший ADJ amod
, PUNCT punct
что PRON mark
надеяться VERB advcl
. PUNCT punct
он PRON nsubj
нашёл ADJ ROOT
свой DET det
далёкий ADJ amod
дом NOUN obj
. PUNCT punct


 SPACE dep
самый ADJ amod
важный ADJ amod
день NOUN nsubj
начаться VERB ROOT
так ADV advmod
скучный ADJ advmod
и CCONJ cc
уныло VERB conj
, PUNCT punct
а CCONJ cc
закончиться VERB conj
прекрасный ADJ amod
ясный ADJ amod
ощущение NOUN obl
, PUNCT punct
что SCONJ mark
всё PRON nsubj
только PART advmod
начинаться VERB parataxis
. PUNCT punct

In [ ]:
adjs = []
for token in document:
    if token.pos_ == 'ADJ':
        adjs.append(token.lemma_)

In [ ]:
adjs

['осенний',
 'никитский',
 'холодный',
 'двадцатиградусный',
 'ноябрьский',
 'сам',
 'виноватый',
 'странный',
 'старый',
 'никитский',
 'лёгкий',
 'первый',
 'большой',
 'тёмный',
 'чужой',
 'последний',
 'пожилой',
 'важный',
 'трудный',
 'нежный',
 'трусливый',
 'жёлтый',
 'знаменитый',
 'талантливый',
 'молодой',
 'похожий',
 'самого',
 'другой',
 'другими',
 'громкий',
 'звенящий',
 'молоденький',
 'хорошенький',
 'больший',
 'необычный',
 'радостный',
 'беспокойный',
 'ждёт',
 'тихим',
 'нежный',
 'маленький',
 'простой',
 'тёплый',
 'душистый',
 'розовый',
 'сама',
 'равнодушный',
 'спокойный',
 'тонкий',
 'прозрачный',
 'старенький',
 'крошечный',
 'зелёный',
 'голубой',
 'милый',
 'невольный',
 'чужой',
 'тяжёлый',
 'однообразный',
 'неестественный',
 'пошлый',
 'порядочный',
 'должный',
 'фальшивый',
 'бесполезный',
 'нужный',
 'самому',
 'старый',
 'красивый',
 'молодой',
 'умный',
 'похожий',
 'родной',
 'случайный',
 'необходимый',
 'главный',
 'равнодушный',
 'живой',
 'тайный',
 'мгновенный',
 'счастливый',
 'холодный',
 'тёплый',
 'радостный',
 'маленький',
 'милый',
 'старый',
 'тяжёлый',
 'лёгкий',
 'холодный',
 'тёмно',
 'сырой',
 'весенний',
 'нашёл',
 'больший',
 'нашёл',
 'далёкий',
 'самый',
 'важный',
 'скучный',
 'прекрасный',
 'ясный']

In [ ]:
adjs_tally = Counter(adjs)

In [ ]:
adjs_tally.most_common()

[('холодный', 3),
 ('старый', 3),
 ('никитский', 2),
 ('лёгкий', 2),
 ('чужой', 2),
 ('важный', 2),
 ('нежный', 2),
 ('молодой', 2),
 ('похожий', 2),
 ('больший', 2),
 ('радостный', 2),
 ('маленький', 2),
 ('тёплый', 2),
 ('равнодушный', 2),
 ('милый', 2),
 ('тяжёлый', 2),
 ('нашёл', 2),
 ('осенний', 1),
 ('двадцатиградусный', 1),
 ('ноябрьский', 1),
 ('сам', 1),
 ('виноватый', 1),
 ('странный', 1),
 ('первый', 1),
 ('большой', 1),
 ('тёмный', 1),
 ('последний', 1),
 ('пожилой', 1),
 ('трудный', 1),
 ('трусливый', 1),
 ('жёлтый', 1),
 ('знаменитый', 1),
 ('талантливый', 1),
 ('самого', 1),
 ('другой', 1),
 ('другими', 1),
 ('громкий', 1),
 ('звенящий', 1),
 ('молоденький', 1),
 ('хорошенький', 1),
 ('необычный', 1),
 ('беспокойный', 1),
 ('ждёт', 1),
 ('тихим', 1),
 ('простой', 1),
 ('душистый', 1),
 ('розовый', 1),
 ('сама', 1),
 ('спокойный', 1),
 ('тонкий', 1),
 ('прозрачный', 1),
 ('старенький', 1),
 ('крошечный', 1),
 ('зелёный', 1),
 ('голубой', 1),
 ('невольный', 1),
 ('однообразный', 1),
 ('неестественный', 1),
 ('пошлый', 1),
 ('порядочный', 1),
 ('должный', 1),
 ('фальшивый', 1),
 ('бесполезный', 1),
 ('нужный', 1),
 ('самому', 1),
 ('красивый', 1),
 ('умный', 1),
 ('родной', 1),
 ('случайный', 1),
 ('необходимый', 1),
 ('главный', 1),
 ('живой', 1),
 ('тайный', 1),
 ('мгновенный', 1),
 ('счастливый', 1),
 ('тёмно', 1),
 ('сырой', 1),
 ('весенний', 1),
 ('далёкий', 1),
 ('самый', 1),
 ('скучный', 1),
 ('прекрасный', 1),
 ('ясный', 1)]

In [ ]:
df = pd.DataFrame(adjs_tally.most_common(), columns=['adj', 'count'])
df[:100]

                  adj  count
0            холодный      3
1              старый      3
2           никитский      2
3              лёгкий      2
4               чужой      2
5              важный      2
6              нежный      2
7             молодой      2
8             похожий      2
9             больший      2
10          радостный      2
11          маленький      2
12             тёплый      2
13        равнодушный      2
14              милый      2
15            тяжёлый      2
16              нашёл      2
17            осенний      1
18  двадцатиградусный      1
19         ноябрьский      1
20                сам      1
21          виноватый      1
22           странный      1
23             первый      1
24            большой      1
25             тёмный      1
26          последний      1
27            пожилой      1
28            трудный      1
29          трусливый      1
30             жёлтый      1
31         знаменитый      1
32        талантливый      1
33             самого      1
34             другой      1
35            другими      1
36            громкий      1
37           звенящий      1
38        молоденький      1
39        хорошенький      1
40          необычный      1
41        беспокойный      1
42               ждёт      1
43              тихим      1
44            простой      1
45           душистый      1
46            розовый      1
47               сама      1
48          спокойный      1
49             тонкий      1
50         прозрачный      1
51         старенький      1
52          крошечный      1
53            зелёный      1
54            голубой      1
55          невольный      1
56       однообразный      1
57     неестественный      1
58             пошлый      1
59         порядочный      1
60            должный      1
61          фальшивый      1
62        бесполезный      1
63             нужный      1
64             самому      1
65           красивый      1
66              умный      1
67             родной      1
68          случайный      1
69        необходимый      1
70            главный      1
71              живой      1
72             тайный      1
73         мгновенный      1
74         счастливый      1
75              тёмно      1
76              сырой      1
77           весенний      1
78            далёкий      1
79              самый      1
80            скучный      1
81         прекрасный      1
82              ясный      1

In [ ]:
nouns = []
for token in document:
    if token.pos_ == 'NOUN':
        nouns.append(token.lemma_)

nouns_tally = Counter(nouns)

df = pd.DataFrame(nouns_tally.most_common(), columns=['noun', 'count'])
df[:100]

           noun  count
0       человек      4
1         визит      3
2          глаз      3
3          день      2
4          окно      2
5       девушка      2
6        взгляд      2
7         связь      2
8      квартира      1
9          снег      1
10        город      1
11     экономка      1
12       письмо      1
13       почерк      1
14         лист      1
15          нём      1
16         цель      1
17        мысль      1
18       звонок      1
19        порог      1
20       внучка      1
21      бабушка      1
22        голос      1
23      комната      1
24         хлеб      1
25       кресло      1
26         рука      1
27       колено      1
28       столик      1
29       кактус      1
30       горшок      1
31      подарок      1
32     разговор      1
33        слово      1
34    поведение      1
35     неправда      1
36   фотография      1
37        капля      1
38         вода      1
39          дед      1
40      встреча      1
41        жизнь      1
42     ожидание      1
43          миг      1
44         ужас      1
45  одиночество      1
46      чувство      1
47          мир      1
48      женщина      1
49       память      1
50        кровь      1
51       сердце      1
52        улица      1
53         душа      1
54        птица      1
55          дом      1
56     ощущение      1

In [ ]:
verbs = [token.lemma_ for token in document if token.pos_ == 'VERB']

verbs_tally = Counter(verbs)

df = pd.DataFrame(verbs_tally.most_common(), columns=['verb', 'count'])
df[:100]

             verb  count
0     чувствовать      2
1          стоять      2
2            быть      1
3          стоить      1
4        неодетый      1
5       кружиться      1
6          делать      1
7       вспомнить      1
8       упоминать      1
9        прервать      1
10          сиять      1
11        сказать      1
12     пропахнуть      1
13         сидеть      1
14         лежать      1
15       казаться      1
16       говорить      1
17        звучать      1
18         упасть      1
19          знать      1
20         понять      1
21      взглянуть      1
22       смотреть      1
23        полными      1
24  почувствовать      1
25        хранить      1
26           уйти      1
27           петь      1
28      надеяться      1
29       начаться      1
30          уныло      1
31    закончиться      1
32     начинаться      1

In [ ]:
https://melaniewalsh.github.io/Intro-Cultural-Analytics/05-Text-Analysis/Multilingual/Russian/02-Named-Entity-Recognition-Russian.html